fix delete in ThreadedRegexVM
This compiler error only shows up in the meson build, not in the make
build. I don't know why, and I'm not sure if this will cause a memory
leak.

    [10/16] Compiling C++ object kak.p/src_normal.cc.o
    FAILED: kak.p/src_normal.cc.o
    clang++ -Ikak.p -I. -I.. -Isrc -I../src -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -std=c++2a -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-sign-compare -MD -MQ kak.p/src_normal.cc.o -MF kak.p/src_normal.cc.o.d -o kak.p/src_normal.cc.o -c ../src/normal.cc
    In file included from ../src/normal.cc:17:
    In file included from ../src/regex.hh:5:
    ../src/regex_impl.hh:245:13: error: no matching function for call to 'operator delete'
      245 |             operator delete(saves.pos, m_program.save_count * sizeof(Iterator));